In [1]:
import numpy as np


In [5]:
def greet(name):
    print(f"Hello, {name}!")

greet("Walt")

greet("ginnocarlo esse guardianee es esspacio as univeszio")


Hello, Walt!
Hello, ginnocarlo esse guardianee es esspacio as univeszio!


In [18]:
def add_numbers(a, b):
    return a + b
print(add_numbers(3, 5))

8


In [8]:
def calculate_bmi(weight, height):
    bmi = weight / (height ** 2)
    return bmi
bmi_result = calculate_bmi(70, 1.75)

print(calculate_bmi(70, 1.75))




22.857142857142858


In [1]:


def calculate_total(amount, Trate = 0.05):
    return amount * (1 + Trate)


print(f"Total: {calculate_total(100):.2f}")
print(f"Total: {calculate_total(200, 0.12):.2f}")

Total: 105.00
Total: 224.00


In [3]:

price = float(input("Enter the original price: "))


def apply_discount(price, discount_percent):

    return price * (1 - discount_percent / 100)

res = apply_discount(price, 10) 
print(f"price + discount: {res:.2f}")



price + discount: 11775771758.70


In [7]:
def norm (name):
    return ' '.join(name.strip().split()).title()

print(norm("   walt    wimer  HerNANDez"))

Walt Wimer Hernandez


In [10]:
def basic_stats(numbers):
    count = len(numbers)
    total = sum(numbers)
    mean = total / count if count > 0 else None
    return count, total, mean

print(basic_stats([10, 20, 30]))


(3, 60, 20.0)


In [12]:
def apply_tax(amounts, tax_rate=0.1):
    return [round(amt * (1 + tax_rate), 2) for amt in amounts]

print(apply_tax([100, 200, 350], 0.05))

[105.0, 210.0, 367.5]


In [13]:
def process_score(score, max_score=100):
    if score < 0 or score > max_score:
        return None
    return round((score / max_score) * 100, 1)

print(process_score(85))
print(process_score(150))

85.0
None


In [15]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print(arr.dtype)

[10 20 30 40 50]
int64


In [17]:

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])    # First
print(arr[-1])   # Last
print(arr[1:4])  # Slice

10
50
[20 30 40]


In [19]:

sales = np.array([120, 250, 90, 400, 60])
high_sales = sales[sales > 100]
print(high_sales)

[120 250 400]


In [21]:
prices = np.array([100.0, 200.0, 300.0])
taxed = prices* 1.05
discounted = prices - (prices * 0.1)

print(taxed)
print(discounted)


[105. 210. 315.]
[ 90. 180. 270.]
